import { Router } from 'express';
import { healthRouter } from './health.routes';
import { authRouter } from './auth.routes';
import { adminRouter } from './admin.routes';
import { categoryRouter } from './category.routes';
import { heroRouter } from './hero.routes';
import { productRouter } from './product.routes';
import { cartRouter } from './cart.routes';
import { wishlistRouter } from './wishlist.routes';
import { addressRouter } from './address.routes';
import { orderRouter } from './order.routes';
import { paymentRouter } from './payment.routes';
import { shipmentRouter } from './shipment.routes';
import { reviewRouter } from './review.routes';
import { couponRouter } from './coupon.routes';
import { returnRouter } from './return.routes';
import { notificationRouter } from './notification.routes';

export const v1Router = Router();

v1Router.use(healthRouter);
v1Router.use('/auth', authRouter);
v1Router.use('/admin', adminRouter);
v1Router.use('/categories', categoryRouter);
v1Router.use('/hero', heroRouter);
v1Router.use('/products', productRouter);
v1Router.use('/cart', cartRouter);
v1Router.use('/wishlist', wishlistRouter);
v1Router.use('/addresses', addressRouter);
v1Router.use('/orders', orderRouter);
v1Router.use('/payments', paymentRouter);
v1Router.use('/shipments', shipmentRouter);
v1Router.use('/reviews', reviewRouter);
v1Router.use('/coupons', couponRouter);
v1Router.use('/returns', returnRouter);
v1Router.use('/notifications', notificationRouter);
